@FootballTransferApi_HostAddress = https://localhost:7176


##################################################
### View All News
##################################################

GET {{FootballTransferApi_HostAddress}}/api/news
Accept: application/json

###

GET {{FootballTransferApi_HostAddress}}/api/transfers
Accept: application/json

##################################################

POST {{FootballTransferApi_HostAddress}}/api/news/process/6

###
##################################################
### 1. Crawl Real BBC News
##################################################

GET {{FootballTransferApi_HostAddress}}/api/crawler
Accept: application/json

###

##################################################
### 2. View All Crawled News
##################################################

GET {{FootballTransferApi_HostAddress}}/api/news
Accept: application/json

###

##################################################
### 3. Process One Real BBC News
### 先执行第2步
### 找到真实新闻ID
### 然后修改下面数字
##################################################

POST {{FootballTransferApi_HostAddress}}/api/news/process/55

###

##################################################
### 4. Process All Unprocessed News
##################################################

POST {{FootballTransferApi_HostAddress}}/api/news/process-all

###

##################################################
### 5. View Processed News Detail
### 修改成你的真实ID
##################################################

GET {{FootballTransferApi_HostAddress}}/api/news/18
Accept: application/json

###

##################################################
### 6. View Extracted Transfers
##################################################

GET {{FootballTransferApi_HostAddress}}/api/news/transfers
Accept: application/json

###

##################################################
### 7. View Latest Transfers
##################################################

GET {{FootballTransferApi_HostAddress}}/api/news/latest-transfers
Accept: application/json

###

##################################################
### 8. Search By Club
##################################################

GET {{FootballTransferApi_HostAddress}}/api/news/search?keyword=Liverpool
Accept: application/json

###

##################################################
### 9. Search By Player
##################################################

GET {{FootballTransferApi_HostAddress}}/api/news/search?keyword=Diomande
Accept: application/json

###