@FootballTransferApi_HostAddress = https://localhost:7176


##################################################
### View All News
##################################################

GET {{FootballTransferApi_HostAddress}}/api/news
Accept: application/json

###

GET {{FootballTransferApi_HostAddress}}/api/transfers
Accept: application/json

##################################################
POST {{FootballTransferApi_HostAddress}}/api/crawler/crawl
Accept: application/json

################################################
### 4. Process Unprocessed News
################################################
POST {{FootballTransferApi_HostAddress}}/api/ai/process-unprocessed/15
Accept: application/json